<Project Sdk="Microsoft.NET.Sdk.Razor">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<StaticWebAssetBasePath>App_Plugins/UmbracoCommunityAutomateSkoda</StaticWebAssetBasePath>
	</PropertyGroup>


	<ItemGroup>
		<SupportedPlatform Include="browser" />
	</ItemGroup>
</Project>
